### ISSUE TITLE
是否支持Postgresql 不同schema

### ISSUE THREAD

**Issue by defp** [go-gorm/gen#506]
https://www.postgresql.org/docs/current/ddl-schemas.html

```
		g.GenerateModel("business.drug_package_mapping_task"),

```

```

2022/06/30 17:33:58 /Users/lidashuang/.asdf/installs/golang/1.18/packages/pkg/mod/gorm.io/gen@v0.3.8/generator.go:138
[error] generate struct from table fail: model name "Business.DrugPackageMappingTask" is invalid: model name cannot contains invalid character
panic: generate struct fail

goroutine 1 [running]:
gorm.io/gen.(*Generator).GenerateModelAs(0x14000254380, {0x104c4ced1, 0x22}, {0x140002d6780, 0x1f}, {0x0, 0x0, 0x1400019bee8?})
	/Users/lidashuang/.asdf/installs/golang/1.18/packages/pkg/mod/gorm.io/gen@v0.3.8/generator.go:139 +0x380
gorm.io/gen.(*Generator).GenerateModel(0x14000254380, {0x104c4ced1, 0x22}, {0x0, 0x0, 0x0})
	/Users/lidashuang/.asdf/installs/golang/1.18/packages/pkg/mod/gorm.io/gen@v0.3.8/generator.go:103 +0x74
main.main()
	/Users/lidashuang/Projects/nocode/bluespace-saas/cmd/generate/generate.go:65 +0x3dc
exit status 2
```

**Comment by defp** [comment]
`		g.GenerateModelAs("business.drug_package_mapping_task", "DrugPackageMappingTask"),
`
