### ISSUE TITLE
[error] generate model struct fail: cannot format file: /path/to/Repositories/model/tasks.gen.go:23:2: expected '}', found 0 (and 1 more errors)

### ISSUE THREAD

**Issue by chase-isabelle-roostify** [go-gorm/gen#583]
## GORM Playground Link

no link - this is a bug in the cli binary

## Description

looks like the tool is failing to format some generated code

```
gentool --db postgres --dsn 'host=localhost user=user password=password dbname=db/development port=5432 sslmode=disable' --tables 'tasks'

...

2022/07/29 16:21:19 /path/to/go/pkg/mod/gorm.io/gen@v0.3.13/generator.go:254
[error] generate model struct fail: cannot format file: /path/to/Repositories/model/tasks.gen.go:23:2: expected '}', found 0 (and 1 more errors)
panic: generate model struct fail

goroutine 1 [running]:
gorm.io/gen.(*Generator).Execute(0x1400043c380)
	/path/to/go/pkg/mod/gorm.io/gen@v0.3.13/generator.go:255 +0x1f8
main.main()
	/path/to/go/pkg/mod/gorm.io/gen@v0.3.13/tools/gentool/gentool.go:207 +0x238
```

**Comment by chase-isabelle-roostify** [comment]
This may actually be caused by a column named `0`.

**Comment by chase-isabelle-roostify** [comment]
seems there's a similar error with other tables

```
gentool --db postgres --dsn 'host=localhost user=user password=password dbname=db/development port=5432 sslmode=disable' --tables 'users'

2022/07/29 22:34:11 /path/to/go/pkg/mod/gorm.io/driver/postgres@v1.3.8/migrator.go:369 SLOW SQL >= 200ms
[211.973ms] [rows:-] SELECT c.column_name, c.is_nullable = 'YES', c.udt_name, c.character_maximum_length, c.numeric_precision, c.numeric_precision_radix, c.numeric_scale, c.datetime_precision, 8 * typlen, c.column_default, pd.description FROM information_schema.columns AS c JOIN pg_type AS pgt ON c.udt_name = pgt.typname LEFT JOIN pg_catalog.pg_description as pd ON pd.objsubid = c.ordinal_position AND pd.objoid = (SELECT oid FROM pg_catalog.pg_class WHERE relname = c.table_name AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = c.table_schema)) where table_catalog = 'db/development' AND table_schema = CURRENT_SCHEMA() AND table_name = 'users'

2022/07/29 22:34:11 /path/to/go/pkg/mod/gorm.io/driver/postgres@v1.3.8/migrator.go:439 SLOW SQL >= 200ms
[214.748ms] [rows:-] SELECT c.column_name, constraint_type FROM information_schema.table_constraints tc JOIN information_schema.constraint_column_usage AS ccu USING (constraint_schema, constraint_name) JOIN information_schema.columns AS c ON c.table_schema = tc.constraint_schema AND tc.table_name = c.table_name AND ccu.column_name = c.column_name WHERE constraint_type IN ('PRIMARY KEY', 'UNIQUE') AND c.table_catalog = 'db/development' AND c.table_schema = CURRENT_SCHEMA() AND c.table_name = 'users'
2022/07/29 22:34:11 got 96 columns from table <users>
2022/07/29 22:34:11 Start generating code.
2022/07/29 22:34:11 generate model file(table <users> -> {model.User}): /path/to/Repositories/model/users.gen.go

2022/07/29 22:34:11 /path/to/go/pkg/mod/gorm.io/gen@v0.3.13/generator.go:529
[warn] parse model pkg path fail: err: exit status 1: stderr: go: go.mod file not found in current directory or any parent directory; see 'go help modules'
Format fail: 6 /path/to/Repositories/project/users.gen.go:6:15: expected ';', found '-'
1 // Code generated by gorm.io/gen. DO NOT EDIT.
2 // Code generated by gorm.io/gen. DO NOT EDIT.
3 // Code generated by gorm.io/gen. DO NOT EDIT.
4
5 package project
6
7 import(
8 	"context"
9 "database/sql"
10 "strings"
11
2022/07/29 22:34:11 generate query file: /path/to/Repositories/project/users.gen.go

2022/07/29 22:34:11 /path/to/go/pkg/mod/gorm.io/gen@v0.3.13/generator.go:259
[error] generate query code fail: cannot format file: /path/to/Repositories/project/users.gen.go:6:15: expected ';', found '-'
panic: generate query code fail

goroutine 1 [running]:
gorm.io/gen.(*Generator).Execute(0x1400043c380)
	/path/to/go/pkg/mod/gorm.io/gen@v0.3.13/generator.go:260 +0x13c
main.main()
	/path/to/go/pkg/mod/gorm.io/gen@v0.3.13/tools/gentool/gentool.go:207 +0x238
```

**Comment by chase-isabelle-roostify** [comment]
even though the tool produces this error, it seems like the generated code is actually fine. `go fmt ../model/users.gen.go` produces no errors, and a quick inspection of the code looks ok.

**Comment by chase-isabelle-roostify** [comment]
on further inspection of the error trace, this might be a gorm bug, not a bug with this tool

**Comment by chase-isabelle-roostify** [comment]
for some reason, this bug exists in the binary; however, when running via `go run tools/gentool/gentool.go` it does not.

**Comment by qqxhb** [comment]
@chase-isabelle-roostify 
`gen.FieldRename`
 try this model option

But I prefer you to change the field name

**Comment by chase-isabelle-roostify** [comment]
yea, it's definitely an edge case and a bad field name; but, i'm keeping the ticket open since it is _technically_ a valid field name. if i have time i will see if i can apply a patch and submit a pr. thanks, @qqxhb .

**Comment by BCSF15M004** [comment]
I got the same error:
![image](https://user-images.githubusercontent.com/37077032/231384653-7e72ec42-368a-4b02-b3b3-e980249e727a.png)

But when I provided the folder path and file name like this:
`-outPath ./generatedtructs -outFile "generatedStructs.go"`

The error got resolved for me.

**Comment by cha0ran** [comment]
I have encountered a similar error: "[error] generate model struct fail: cannot format file: /path/tableXXX.gen.go:48:5: expected '}', found 1688 (and 1 more errors) panic: generate model struct fail." It appears that the tool does not support field names with numbers, but this is allowed in MySQL. I hope to find a solution for this issue.

**Comment by cha0ran** [comment]
Oh, I think I understand now. In Go's naming conventions, identifiers cannot start with a number. So, this is probably an unsolvable problem. 🫠

**Comment by cha0ran** [comment]
But I generated it using a binary file, so I can't use the `gen.FieldRename` method, right? @qqxhb

**Comment by qqxhb** [comment]
> But I generated it using a binary file, so I can't use the `gen.FieldRename` method, right? @qqxhb

Yes. The binary is not very flexible.
