### ISSUE TITLE
tag v0.3.19 will panic when use GenerateModel in Windows

### ISSUE THREAD

**Issue by ConanYu** [go-gorm/gen#746]
## GORM Playground Link

https://github.com/ConanYu/gorm-playground/pull/1

## Description

golang version: 1.19.5
os: windows
arch: amd64
project path: `C:\code\gorm-playground`
playground output:
```
$ sh test.sh 
git clone --depth 1 -b master https://github.com/go-gorm/gorm.git
Cloning into 'gorm'...
remote: Enumerating objects: 177, done.
remote: Counting objects: 100% (177/177), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 177 (delta 12), reused 43 (delta 5), pack-reused 0R
Receiving objects: 100% (177/177), 207.26 KiB | 453.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
gorm-playground_mssql_1 is up-to-date
gorm-playground_postgres_1 is up-to-date
gorm-playground_mysql_1 is up-to-date   
starting...
testing mysql...
2023/01/13 18:54:42 testing mysql...
=== RUN   TestGORM

2023/01/13 18:54:44 C:/code/gorm-playground/main_test.go:20
[13.265ms] [rows:1] INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`age`,`birthday`,`company_id`,`manager_id`,`active`) VALUES ('2023-01-13 18:54:
44.327','2023-01-13 18:54:44.327',NULL,'jinzhu',0,NULL,NULL,NULL,false)

2023/01/13 18:54:44 C:/code/gorm-playground/main_test.go:23
[2.737ms] [rows:1] SELECT * FROM `users` WHERE `users`.`id` = 1 AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1
--- PASS: TestGORM (0.02s)
=== RUN   TestGormGen
C:/code/gorm-playground/model

2023/01/13 18:54:44 C:/Users/Admin/go/pkg/mod/gorm.io/driver/mysql@v1.4.5/migrator.go:259
[1.072ms] [rows:-] SELECT DATABASE()

2023/01/13 18:54:44 C:/Users/Admin/go/pkg/mod/gorm.io/driver/mysql@v1.4.5/migrator.go:262
[3.799ms] [rows:1] SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'gorm%' ORDER BY SCHEMA_NAME='gorm' DESC,SCHEMA_NAME limit 1

2023/01/13 18:54:44 C:/Users/Admin/go/pkg/mod/gorm.io/driver/mysql@v1.4.5/migrator.go:168
[1.643ms] [rows:-] SELECT * FROM `users` LIMIT 1

2023/01/13 18:54:44 C:/Users/Admin/go/pkg/mod/gorm.io/driver/mysql@v1.4.5/migrator.go:190
[11.804ms] [rows:-] SELECT column_name, column_default, is_nullable = 'YES', data_type, character_maximum_length, column_type, column_key, extra, column_comment, numeric_precision, numeric_scale , datetime_precision FROM information_schema.columns WHERE table_schema = 'gorm' AND table_name = 'users' ORDER BY ORDINAL_POSITION

2023/01/13 18:54:44 C:/Users/Admin/go/pkg/mod/gorm.io/gen@v0.3.19/generator.go:274
[info] got 10 columns from table <users>
2023/01/13 18:54:44 got 10 columns from table <users>

2023/01/13 18:54:44 C:/Users/Admin/go/pkg/mod/gorm.io/gen@v0.3.19/generator.go:274
[info] Start generating code.
2023/01/13 18:54:44 Start generating code.

2023/01/13 18:54:44 C:/Users/Admin/go/pkg/mod/gorm.io/gen@v0.3.19/generator.go:259
[error] generate model struct fail: create model pkg path(C:\code\C:\code\gorm-playground\model\) fail: mkdir C:\code\C:: The filename, directory name, or volume label syntax is incorrect.
--- FAIL: TestGormGen (0.05s)
panic: generate model struct fail [recovered]
        panic: generate model struct fail

goroutine 24 [running]:
testing.tRunner.func1.2({0x1205fa0, 0x14ede40})
        C:/Users/Admin/go/go1.19.5/src/testing/testing.go:1396 +0x372
testing.tRunner.func1()
        C:/Users/Admin/go/go1.19.5/src/testing/testing.go:1399 +0x5f0
panic({0x1205fa0, 0x14ede40})
        C:/Users/Admin/go/go1.19.5/src/runtime/panic.go:890 +0x262
gorm.io/gen.(*Generator).Execute(0xc00020e000)
        C:/Users/Admin/go/pkg/mod/gorm.io/gen@v0.3.19/generator.go:260 +0x357
gorm.io/playground.TestGormGen(0x0?)
        C:/code/gorm-playground/main_test.go:39 +0x1fa
testing.tRunner(0xc000085520, 0x13999c0)
        C:/Users/Admin/go/go1.19.5/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
        C:/Users/Admin/go/go1.19.5/src/testing/testing.go:1493 +0x75e
FAIL    gorm.io/playground      2.907s
FAIL
```

I think the issue comes from https://github.com/go-gorm/gen/pull/709.
This was not an issue before v0.3.18.

**Comment by qqxhb** [comment]
#806
