### ISSUE TITLE
Postgres `json` field type is generated as `string`

### ISSUE THREAD

**Issue by mbana** [go-gorm/gen#872]
Given this schema:

```sql
CREATE TABLE "Party_Metadata" (
	party_id bigint primary key not NULL,
	metadata json NULL
);
```

This command to generate the models etc.:

```sh
gentool -db postgres -dsn "host=localhost port=5432 user=cynergy dbname=customer password=secret connect_timeout=10 sslmode=disable search_path=public" -tables "" -outPath ./dao -fieldWithTypeTag -fieldNullable
```

The generated code does not seem type-safe:

```go
package main

import (
	"context"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"github.com/mbana/golang/go-germ/gen/dao"
	"github.com/mbana/golang/go-germ/gen/model"
)

func main() {
	dsn := "host=localhost port=5432 user=cynergy dbname=customer password=secret connect_timeout=10 sslmode=disable search_path=public"

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		panic(err)
	}

	metadata := `
some str
`

	// u refer to query.user
	p := model.PartyMetadatum{
		PartyID:  2,
		Metadata: strPoint(metadata),
	}

	ctx := context.Background()

	u := dao.Use(db)
	if err := u.WithContext(ctx).PartyMetadatum.Create(&p); err != nil {
		panic(err)
	}
}

func strPoint(str string) *string {
	return &str
}
```

Output:

```sh
$ go run main.go                                                                                  

2023/05/26 18:03:40 /home/mbana/work/cynergybank.co.uk/customer-api/dao/party_metadata.gen.go:203 ERROR: invalid input syntax for type json (SQLSTATE 22P02)
[6.094ms] [rows:0] INSERT INTO "Party_Metadata" ("metadata","party_id") VALUES ('
some str
',2) RETURNING "party_id"
panic: ERROR: invalid input syntax for type json (SQLSTATE 22P02)

goroutine 1 [running]:
main.main()
	/home/mbana/work/cynergybank.co.uk/customer-api/main.go:35 +0x227
exit status 2
```

---

The model generated is:

```go
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePartyMetadatum = "Party_Metadata"

// PartyMetadatum mapped from table <Party_Metadata>
type PartyMetadatum struct {
	PartyID  int64   `gorm:"column:party_id;type:bigint;primaryKey" json:"party_id"`
	Metadata *string `gorm:"column:metadata;type:json" json:"metadata"`
}

// TableName PartyMetadatum's table name
func (*PartyMetadatum) TableName() string {
	return TableNamePartyMetadatum
}
```

Shouldn't the type be `json.RawMessage`?

**Comment by jinzhu** [comment]
Hi @mbana 

This should be caused metadata's value is not a valid JSON object.

**Comment by mbana** [comment]
Hold on a minute please, why is it allowing to even insert a `string` in the first place whilst the types in the DB are `json`?
